// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baxnczbtheknzpoerpfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJheG5jemJ0aGVrbnpwb2VycGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODQxNjIsImV4cCI6MjA2MDA2MDE2Mn0.k7wMmYm15ALHBP-uSBpEFcteKOnnMRbEn8ax2wuDsJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);